<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
    
    <!-- to be called on chapter XMLs as generated by build.sh: keep the original IDs -->
    <xsl:template match="/">
        <div type="chapter">
            <xsl:for-each select="//div[@class='chapter'][1]">
                <xsl:attribute name="id">
                    <xsl:value-of select="@id"/>
                </xsl:attribute>
                <xsl:apply-templates/>
            </xsl:for-each>
        </div>
    </xsl:template>
    
    <xsl:template match="h3">
        <seg type="headline">
            <xsl:apply-templates/>
        </seg>
    </xsl:template>
    
    <xsl:template match="p/span">
        <xsl:variable name="id" select="sup[1]/@id"/>
        <seg type="verse">
            <xsl:if test="$id!=''">
                <xsl:attribute name="id">
                    <xsl:value-of select="$id"/>
                </xsl:attribute>
            </xsl:if>
            <xsl:apply-templates/>
        </seg>
    </xsl:template>
    
    <xsl:template match="h5|a|sup|text()[normalize-space(.)='']"/>

    <!-- encoding corrections -->
    <xsl:template match="text()">
        <xsl:value-of select='normalize-space(translate(.,"&#226;","&apos;"))'/>        
    </xsl:template>

    <xsl:template match="*">
        <xsl:apply-templates/>
    </xsl:template>


</xsl:stylesheet>
